import { createHttpHandler } from '@trpc/server/adapters/http';
import { router } from './api';

addEventListener('fetch', (event) => {
	event.respondWith(
	  createHttpHandler({
		router,
		createContext: () => null, // or your context creation logic here
	  })(event.request),
	);
  });
  
export default {
	async fetch(request) {
	  const html = `<!DOCTYPE html>
		  <body>
			<h1>Hello World</h1>
			<p>This markup was generated by Heezay.</p>
		  </body>`;
  
	  return new Response(html, {
		headers: {
		  "content-type": "text/html;charset=UTF-8",
		},
	  });
	},
  };
